[package]
name = "t-rex-gdal"
version = "0.9.9"
description = "vector tile server"
repository = "https://github.com/t-rex-tileserver/t-rex"
readme = "../README.md"
license = "MIT"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]
edition = "2018"
workspace = ".."

[lib]
doctest = false

[dependencies]
gdal = "0.9"
gdal-sys = "0.5"
# Appveyor Windows build with GDAL 2.2.4 fails:
# gdal-sys = { version = "0.5", features = ["bindgen"] }
# error[E0308]: mismatched types
#    --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\gdal-0.9.0\src\raster\rasterband.rs:101:27
#     |
# 101 |             eResampleAlg: map_resample_alg(&e_resample_alg),
#     |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `u32`
# error[E0308]: mismatched types
#    --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\gdal-0.9.0\src\vector\geometry.rs:101:17
#     |
# 101 |                 wkb.as_ptr() as *const std::ffi::c_void,
#     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ types differ in mutability
#     |
#     = note: expected raw pointer `*mut u8`
#                found raw pointer `*const c_void`
# error: aborting due to 2 previous errors
log = "0.4"

[dependencies.tile-grid]
path = "../tile-grid"

[dependencies.t-rex-core]
path = "../t-rex-core"
